# Generated by Django 2.2.7 on 2019-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushibar', '0004_blogpost_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellidos', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=8)),
                ('comensales', models.IntegerField()),
                ('nroContacto', models.CharField(max_length=16)),
                ('correo', models.CharField(max_length=256)),
            ],
        ),
    ]
