# Generated by Django 2.2.7 on 2019-12-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushibar', '0005_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=256)),
                ('nroContacto', models.CharField(max_length=16)),
                ('cv', models.FileField(upload_to='cv/')),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(),
        ),
    ]
